@startuml
skinparam linetype ortho
entity AvailableItemsArr {
	  * Индекс массива
	  --
	  * Ссылка на изображение
	  * Название товара
	  * Цена товара
}

note right of AvailableItemsArr 
**__Массив JS__**
Хранит информацию о доступных товарах.
Заполняется на этапе 
инициализации веб-приложения.
end note

entity CartArr {
	  * Индекс массива AvailableItems <<FK>>
	  --
	  * Количество товара
	  * Стоимость товара
	  * Номер строки CartTable <<FK>>
}

note right of CartArr 
**__Массив JS__**
Хранит информацию о товарах, 
добавленных в корзину.
Заполняется и редактируется
пользователем при помощи 
панели управления.
end note

entity CartTable {
	  * Номер строки в таблице
	  --
	  * Ссылка на изображение
	  * Название товара
	  * Цена
	  * Количество
	  * Стоимость
}

note right of CartTable 
**__Таблица HTML__**
Расположена во фрейме Cart.
Отображает информацию о товарах
в корзине для пользователя.
Формируется автоматически.
end note

AvailableItemsArr ||--o| CartArr
CartArr ||--|| CartTable

@enduml
